title: Pallavi Nigam
logo: /assets/img/logo.png
description: 
<p alingn = "center">
I have total 10+ years of expierenice, working as associate architect on cloud 
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
